# ======================================================
# dnsmasq PXE 配置
# 提供 DHCP + TFTP + ProxyDHCP 服务
# ======================================================

# 监听的网络接口
interface=ens33
bind-dynamic

# ----- DHCP 服务 -----
# 启用 DHCP（如果网络已有 DHCP，注释掉以下两行，只保留 ProxyDHCP）
dhcp-range=192.168.1.200,192.168.1.250,12h
dhcp-option=3,192.168.1.1
dhcp-option=6,114.114.114.114

# ----- TFTP 服务 -----
enable-tftp
tftp-root=/srv/tftp
#tftp-secure

# ----- PXE/BOOTP -----
# BIOS PXE 启动
dhcp-boot=pxelinux.0

# UEFI PXE 启动（根据客户端架构选择不同启动文件）
dhcp-match=set:efi-x64,option:client-arch,7
dhcp-match=set:efi-x64,option:client-arch,9
dhcp-match=set:efi-ia32,option:client-arch,6
dhcp-boot=tag:efi-x64,efi/bootx64.efi
dhcp-boot=tag:efi-ia32,efi/bootia32.efi

# iPXE 回退
dhcp-userclass=set:ipxe,iPXE
dhcp-boot=tag:ipxe,http://192.168.1.14/ipxe.php

# 日志
log-dhcp
log-facility=/var/log/pxe/dnsmasq.log

# ARM64 UEFI PXE 启动
dhcp-match=set:efi-arm64,option:client-arch,11
dhcp-boot=tag:efi-arm64,efi/bootaa64.efi
