# iSCSI Target Configuration

<target iqn.2026-07.local.pxe:windows11>
    backing-store /srv/iscsi/windows11.img
    initiator-address 192.168.1.0/24
    incominguser pxeuser P@ssw0rd
</target>

<target iqn.2026-07.local.pxe:ubuntu>
    backing-store /srv/iscsi/ubuntu-root.img
    initiator-address 192.168.1.0/24
    incominguser ubuntu P@ssw0rd
</target>
